version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.12.7

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            go get -u golang.org/x/lint/golint
      - run: make lint
      - run: make test
      - run: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
